language: node_js
node_js:
  - "6"

sudo: false

deploy:
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: GadahtMR6nr/y/9FdkcPBdiQR636YG57je45wh+lKR0aOTaEHmXWxbrXxmwvu7bzXTKnCeQC2agxQdiZHNM2KoFoPgjeFBIX+C/KAT2A0XSlp8fiimN8Kq4kXvMulXcb8SD7gQp4bR1WR8Jya1LBDp+xtABRPxOrmp8jHBZZKg8=
  on:
    tags: true
    repo: Turbo87/webpack-notifier
